spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: subscription
          uri: lb://subscription
          predicates:
            - Path=/api-v1/sub/**
          filters:
            - RewritePath=/api-v1/sub/(?<path>.*), /$\{path}
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api-v1/notify/**
          filters:
            - RewritePath=/api-v1/notify/(?<path>.*), /$\{path}
        - id: acquisition
          uri: lb://acquisition
          predicates:
            - Path=/api-v1/acq/**
          filters:
            - RewritePath=/api-v1/acq/(?<path>.*), /$\{path}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
smartfactory:
  rabbitmq:
    mqtt:
      acquisition:
        exchange: mqtt_events
        queue: mqtt_gateway_queue
springdoc:
  swagger-ui:
    urls:
      - name: notification
        url: /v3/api-docs/notification