spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: subscription-service
          uri: lb://subscription
          predicates:
            - Path=/api/v1/sub/**
          filters:
            - RewritePath=/api/v1/sub/(?<path>.*), /$\{path}
        - id: notification-service
          uri: lb://notification
#          uri: http://localhost:8004
          predicates:
            - Path=/api/v1/notify/**
#            - Path=/notification/**
          filters:
            - RewritePath=/api/v1/notify/(?<path>.*), /$\{path}
#            - RewritePath=/notification/(?<path>.*), /$\{path}
        - id: acquisition-service
          uri: lb://acquisition
          predicates:
            - Path=/api/v1/acq/**
          filters:
            - RewritePath=/api/v1/acq/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  rabbitmq:
    host: 192.168.49.5
    port: 5672
    username: admin
    password: admin
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
smartfactory:
  rabbitmq:
    mqtt:
      acquisition:
        exchange: mqtt_events
        queue: mqtt_gateway_queue

springdoc:
  swagger-ui:
    urls:
      - name: notification
        url: /v3/api-docs/notification
#      - name: subscription
#        url: /v3/api-docs/subscription
#      - name: acquisition
#        url: /v3/api-docs/acquisition