spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: subscription
          uri: lb://subscription
          predicates:
            - Path=/subscription/**
          filters:
            - RewritePath=/subscription/(?<path>.*), /$\{path}
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}
        - id: acquisition
          uri: lb://acquisition
          predicates:
            - Path=/acquisition/**
          filters:
            - RewritePath=/acquisition/(?<path>.*), /$\{path}
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: admin
    password: admin
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
smartfactory:
  rabbitmq:
    mqtt:
      acquisition:
        exchange: mqtt_events
        queue: mqtt_gateway_queue
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api.yaml
