spring:
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka

management:
  security:
    session: always
