spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department
          uri: lb://department
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization
          uri: lb://organization
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: ${KEYCLOAK_URL}/auth/realms/smartfactory
          jwkSetUri: ${KEYCLOAK_URL}/auth/realms/smartfactory/protocol/openid-connect/certs
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: admin
    password: admin
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@discovery:8761/eureka
ribbon:
  eureka:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
smartfactory:
  rabbitmq:
    mqtt:
      acquisition:
        exchange: mqtt_events
        queue: mqtt_gateway_queue
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api.yaml
resilience4j:
  circuitbreaker:
    instances:
      core:
        registerHealthIndicator: true
        slidingWindowSize: 2
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 1
        waitDurationInOpenState: 10s
        failureRateThreshold: 10
  ratelimiter:
    instances:
      core:
        limitForPeriod: 2
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
