spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: subscription-service
          uri: lb://subscription
          predicates:
            - Path=/api/v1/subscription/**
          filters:
            - RewritePath=/api/v1/subscription/(?<path>.*), /$\{path}
        - id: notification-service
          uri: lb://notification
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - RewritePath=/api/v1/notification/(?<path>.*), /$\{path}
        - id: acquisition-service
          uri: lb://acquisition
          predicates:
            - Path=/api/v1/acquisition/**
          filters:
            - RewritePath=/api/v1/acquisition/(?<path>.*), /$\{path}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
smartfactory:
  rabbitmq:
    mqtt:
      acquisition:
        exchange: mqtt_events
        queue: mqtt_gateway_queue
springdoc:
  swagger-ui:
    urls:
      - name: notification
        url: /api/v1/notification/v3/api-docs
